name: Test Case

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.18
    
        - name: Run tests
          env:
            API_HOST: localhost
            API_PORT: 5001
            API_PATH: /mta-hosting-optimizer
          run: go test -cover ./...
        
